Fix error when running on logon
When the script was set to run at startup (that is, at logon),
it tried to initialize the TaskbarList object too early, presumably
before the taskbar was ready, and got this error:

Error: (0x80004001) Not implemented

	040: ITaskbarList_VTable := { HrInit: 3, AddTab: 4, DeleteTab: 5, ActivateTab: 6, SetActiveAlt: 7, }
	048: TaskbarList := ComObject(CLSID_TaskbarList, IID_ITaskbarList)
▶	049: ComCall(ITaskbarList_VTable.HrInit, TaskbarList)
	051: TempHiddenWindows := []
	054: {